name: utilities_helper
description: Our first flutter aplication

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^2.0.0
  firebase_auth: ^1.1.2
  firebase_core: ^1.1.0
  cloud_firestore: ^1.0.7
  google_sign_in: ^5.0.2
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  flutter_facebook_login: ^3.0.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  assets:
    - assets/images/
  fonts:
    - family: Rancho
      fonts:
        - asset: fonts/Rancho-Regular.ttf


  uses-material-design: true

